version: '3.9'

services:
  api:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "4000:4000"
    volumes:
      - public:/usr/src/app/public
    environment:
      - NODE_PORT=4000
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_DOCKER_PORT}

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - node-mongo-data:/data/db

  portainer-ce: 
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  node-mongo-data:
  public:
  data: